---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
      - name: k8s-nexus-key
      containers:
      - name: java-app
        image: k8s-nexus-master:8082/java-app:latest
        #imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8090'
spec:
  selector: 
    app: java-app
  type: NodePort  
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32000